### ISSUE TITLE
1 positional argument(s) expected, but 0 found

### ISSUE THREAD

**Issue by srzern** [febryardiansyah/manga_mint#2]
I used 'flutter pub get, upgrade and out dated' commands but i get this error. 

`error - 1 positional argument(s) expected, but 0 found - lib\components\item_big.dart:41:20 - not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\components\item_small.dart:16:20 - not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\components\splash_screen.dart:26:20 - not_enough_positional_arguments
   
   info - Unused import: 'package:mangamint/service/api_service.dart' - lib\repositories\manhua_manhwa_repo.dart:6:8 - unused_import
 
  error - 1 positional argument(s) expected, but 0 found - lib\screens\chapter_screen\chapter_screen.dart:66:20 - not_enough_positional_arguments
  
  error - 1 positional argument(s) expected, but 0 found - lib\screens\detail_screen\manga_detail_screen.dart:89:20 -

  error - 1 positional argument(s) expected, but 0 found - lib\screens\home_screens\home_screen.dart:35:20 - not_enough_positional_arguments    
  
  error - 1 positional argument(s) expected, but 0 found - lib\screens\home_screens\my_carousel.dart:21:20 - not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\screens\lainnya_screen\lainnya_screen.dart:59:20 - not_enough_positional_arguments 

  error - 1 positional argument(s) expected, but 0 found - lib\screens\list_manga_screen\manhua_category.dart:37:20 -
         not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\screens\list_manga_screen\manhwa_category.dart:39:20 -
         not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\screens\list_manga_screen\semuanya_category.dart:37:20 -
         not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\screens\result_screen\manga_by_genre_screen.dart:47:20 -
         not_enough_positional_arguments

  error - 1 positional argument(s) expected, but 0 found - lib\screens\result_screen\result_screen.dart:28:20 - not_enough_positional_arguments   

  error - 1 positional argument(s) expected, but 0 found - lib\screens\result_screen\terpopuler_screen.dart:31:20 -
         not_enough_positional_arguments`

**Comment by febryardiansyah** [comment]
@Reresize Hi, thanks for opening issue. In that case, i've never got those errors. how about when you create new project and install some dependencies using `pub get` ? does this issue appears or not.
I think this issue is related to this https://github.com/flutter/flutter/issues/21319
Thanks

**Comment by srzern** [comment]
Thanks, i tried something new. I remove old project and imorted again. Just run pub get but i get thiss error;
`Launching lib\main.dart on SM A310F in debug mode...
 lib\main.dart

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it.
   Searched Location:
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\src\nullnull\google-services.json
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\src\debug\google-services.json
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\src\nullnullDebug\google-services.json
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\src\nullnull\debug\google-services.json
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\src\debug\nullnull\google-services.json
  C:\Users\Mike_\Desktop\epik_api_proj\no\manga_mint\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 18s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

And I used 'upgrade packages' and get this error in title '
1 positional argument(s) expected, but 0 found'

**Comment by febryardiansyah** [comment]
Ah, i see the problem. I forgot to add firebase tutorial on readme. I'm using firebase to detect user count with analytics.
The google-services.json is missing, it because i didn't public my google-service.json. You can add your google-service.json by following this tutorial https://firebase.google.com/docs/flutter/setup.
Or If you won't to use firebase analytics, you can follow this tutorial :
1. Go to android/build.gradle and delete  `classpath 'com.google.gms:google-services:4.3.3'`
2.  Go to android/app/build.gradle and delete `apply plugin: 'com.google.gms.google-services'` and `implementation 'com.google.firebase:firebase-analytics:17.2.2'`

Hope this works

**Comment by srzern** [comment]
Thanks. It's worked. I add google-services.json and changed applicationId in build.gradle and now i'ts worked perfectly.
